[package]
name = "linkerd-http-metrics"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
test-util = []

[dependencies]
bytes = "1"
futures = { version = "0.3", default-features = false }
http = "1.1"
http-body = "1.0"
hyper = { version = "1.5", features = ["http1", "http2"] }
parking_lot = "0.12"
pin-project = "1"
tokio = { version = "1", features = ["time"] }
tower = "0.4"
tracing = "0.1"

linkerd-error = { path = "../../error" }
linkerd-http-classify = { path = "../classify" }
linkerd-metrics = { path = "../../metrics", features = ["linkerd-stack"] }
linkerd-stack = { path = "../../stack" }
