[package]
name = "linkerd2-timeout"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.1"
linkerd2-stack = { path = "../stack" }
tokio-connect = { git = "https://github.com/carllerche/tokio-connect" }
tokio-timer = "0.2.4"
tower = "0.1"
tracing = "0.1"
