[package]
name = "linkerd2-timeout"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = { version = "0.3", features = ["compat"] }
linkerd2-error = { path = "../error" }
linkerd2-stack = { path = "../stack" }
tracing = "0.1.22"
pin-project = "0.4"
tokio = { version = "1", features = ["time"] }

[dependencies.tower]
version = "0.4"
# disable tower's tracing `log` integration for performance reasons, since we
# will consume tower's traces as traces.
default-features = false
features = [
    "util",
    "make",
]

[dev-dependencies]
tower-test = "0.3"
tokio-test = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
