[package]
name = "linkerd-http-classify"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
futures = { version = "0.3", default-features = false }
http = "0.2"
http-body = "0.4"
pin-project = "1"
tokio = { version = "1", default-features = false }
tracing = "0.1"

linkerd-error = { path = "../../error" }
linkerd-http-box = { path = "../../http/box" }
linkerd-stack = { path = "../../stack" }

[dev-dependencies]
tokio-test = "0.4"
tower-test = "0.4"
linkerd-tracing = { path = "../../tracing", features = ["ansi"] }
