[package]
name = "linkerd-server-policy"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
proto = ["linkerd-http-route/proto", "linkerd2-proxy-api"]

[dependencies]
ipnet = "2"
http = "0.2"
linkerd-http-route = { path = "../http-route" }
linkerd2-proxy-api = { version = "0.5", features = ["inbound"], optional = true }
thiserror = "1"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
