[package]
name = "linkerd-addr"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
http = "0.2"
linkerd-dns-name = { path = "../dns/name" }
thiserror = "1.0"
