[package]
name = "linkerd2-addr"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
http = "0.2"
linkerd2-dns-name = { path = "../dns/name" }
