[package]
name = "linkerd-proxy-spire-client"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
futures = { version = "0.3", default-features = false }
linkerd-error = { path = "../../error" }
linkerd-proxy-http = { path = "../../proxy/http" }
linkerd-identity = { path = "../../identity" }
spiffe-proto = { path = "../../../spiffe-proto" }
linkerd-tonic-watch = { path = "../../tonic-watch" }
linkerd-exp-backoff = { path = "../../exp-backoff" }
linkerd-stack = { path = "../../stack" }
tokio = { version = "1", features = ["time", "sync"] }
tonic = "0.10"
tower = "0.4"
tracing = "0.1"
x509-parser = "0.16.0"
asn1 = { version = "0.6", package = "simple_asn1" }
thiserror = "2"

[dev-dependencies]
rcgen = "0.12.0"
tokio-test = "0.4"
