[package]
name = "linkerd-app-admin"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
The linkerd proxy's admin server.
"""

[features]
default = []
pprof = ["deflate", "dep:pprof"]
log-streaming = ["linkerd-tracing/stream"]

[dependencies]
deflate = { version = "1", optional = true, features = ["gzip"] }
http = "0.2"
hyper = { version = "0.14", features = ["http1", "http2"] }
futures = { version = "0.3", default-features = false }
pprof = { version = "0.13", optional = true, features = ["prost-codec"] }
serde = "1"
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "sync", "parking_lot"] }
tracing = "0.1"

linkerd-app-core = { path = "../core" }
linkerd-app-inbound = { path = "../inbound" }
linkerd-tracing = { path = "../../tracing" }

[dependencies.tower]
version = "0.4"
default-features = false
features = [
    "buffer",
    "make",
    "spawn-ready",
    "timeout",
    "util",
]
