[package]
name = "linkerd-meshtls-verifier"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
tracing = "0.1"
x509-parser = "0.17.0"

linkerd-error = { path = "../../error" }
linkerd-identity = { path = "../../identity" }


[dev-dependencies]
rcgen = "0.13.2"
