[package]
name = "linkerd-meshtls-verifier"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
tracing = { workspace = true }
x509-parser = "0.18.0"

linkerd-error = { path = "../../error" }
linkerd-identity = { path = "../../identity" }


[dev-dependencies]
linkerd-rustls = { path = "../../rustls", features = ["test-util"] }
