[package]
name = "linkerd2-lock"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
A middleware that provides mutual exclusion.
"""

[dependencies]
futures = "0.3"
linkerd2-error = { path = "../error" }
tower = { version = "0.3", default-features = false }
tracing = "0.1"
tokio = { version = "0.2", features = ["sync", "macros"] }

[dev-dependencies]
rand = "0.7"
tracing-futures = { version = "0.1", features = ["std-future"] }
tracing-log = "0.1"
tracing-subscriber = "0.2.5"
tower = { version = "0.3", default-features = false, features = ["util"] }
tokio-test = "0.2"
tower-test = "0.3"