[package]
name = "linkerd-http-prom"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2021"
publish = false
license = "Apache-2.0"
description = """
Tower middleware for Prometheus metrics.
"""

[features]
test-util = []

[dependencies]
futures = { version = "0.3", default-features = false }
http = "0.2"
http-body = "0.4"
parking_lot = "0.12"
pin-project = "1"
prometheus-client = "0.22"
thiserror = "2"
tokio = { version = "1", features = ["time"] }

linkerd-error = { path = "../../error" }
linkerd-http-box = { path = "../box" }
linkerd-metrics = { path = "../../metrics" }
linkerd-stack = { path = "../../stack" }
