[package]
name = "linkerd-buffer"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
futures = "0.3.9"
linkerd-channel = { path = "../channel" }
linkerd-error = { path = "../error" }
tokio = { version = "1", features = ["sync", "time", "macros"] }
tower = { version = "0.4.1", default_features = false, features = ["util"] }
tracing = "0.1.23"
pin-project = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
tower-test = "0.4"
tokio-test = "0.4"
