[package]
name = "linkerd2-buffer"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3"
linkerd2-error = { path = "../error" }
tokio = { version = "0.2", features = ["sync", "stream", "time", "macros"] }
tower = "0.3"
tracing = "0.1"
tracing-futures = { version = "0.1", features = ["std-future"] }
pin-project = "0.4"

[dev-dependencies]
tower-test = "0.3"
tokio-test = "0.2"
