[package]
name = "linkerd2-router"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.1"
indexmap = "1.0.0"
linkerd2-error = { path = "../error" }
linkerd2-stack = { path = "../stack" }
tokio = "0.1.20"
tokio-sync = "0.1.6"
tokio-timer = "0.2.4"
tower = "0.1"
tracing = "0.1.2"
tracing-futures = "0.1"
