[package]
name = "linkerd2-proxy"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = "The main proxy executable"

[dependencies]
futures = "0.1"
linkerd2-app = { path = "../linkerd/app" }
linkerd2-signal = { path = "../linkerd/signal" }
tokio = "0.1.14"
