[package]
name = "linkerd2-proxy"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = "The main proxy executable"

[features]
default = ["multicore", "meshtls-rustls-ring"]
multicore = ["tokio/rt-multi-thread", "num_cpus"]
meshtls-boring = ["linkerd-meshtls/boring"]
meshtls-boring-fips = ["linkerd-meshtls/boring-fips"]
meshtls-rustls-ring = ["linkerd-meshtls/rustls-ring"]
meshtls-rustls-aws-lc = ["linkerd-meshtls/rustls-aws-lc"]
meshtls-rustls-aws-lc-fips = ["linkerd-meshtls/rustls-aws-lc-fips"]
log-streaming = ["linkerd-app/log-streaming"]
pprof = ["linkerd-app/pprof"]

[dependencies]
futures = { version = "0.3", default-features = false }
kubert-prometheus-tokio = { version = "0.1", features = ["rt"] }
linkerd-app = { path = "../linkerd/app" }
linkerd-metrics = { path = "../linkerd/metrics" }
# We don't actually use code from this crate in `main`; it's here only so we can
# control its feature flags.
linkerd-meshtls = { path = "../linkerd/meshtls" }
linkerd-signal = { path = "../linkerd/signal" }
num_cpus = { version = "1", optional = true }
tokio = { version = "1", features = ["rt", "time", "net"] }
tracing = "0.1"

[target.x86_64-unknown-linux-gnu.dependencies]
jemallocator = { version = "0.5" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }
