[package]
name = "linkerd2-proxy"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false
description = "The main proxy executable"

[features]
default = ["multicore", "rustls-tls"]
multicore = ["tokio/rt-multi-thread", "num_cpus"]
rustls-tls = ["linkerd-app/rustls-tls"]
openssl-tls = ["linkerd-app/openssl-tls"]
boring-tls = ["linkerd-app/boring-tls"]

[dependencies]
futures = { version = "0.3", default-features = false }
mimalloc = { version = "0.1.26", optional = true }
num_cpus = { version = "1", optional = true }
linkerd-app = { path = "../linkerd/app" }
linkerd-signal = { path = "../linkerd/signal" }
tokio = { version = "1", features = ["rt", "time", "net"] }
tracing = "0.1.28"
