[package]
name = "linkerd2-proxy"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = "The main proxy executable"

[features]
default = ["multicore", "meshtls-rustls"]
multicore = ["tokio/rt-multi-thread", "num_cpus"]
meshtls-boring = ["linkerd-meshtls/boring"]
meshtls-rustls = ["linkerd-meshtls/rustls"]
log-streaming = ["linkerd-app/log-streaming"]

[dependencies]
futures = { version = "0.3", default-features = false }
num_cpus = { version = "1", optional = true }
linkerd-app = { path = "../linkerd/app" }
# We don't actually use code from this crate in `main`; it's here only so we can
# control its feature flags.
linkerd-meshtls = { path = "../linkerd/meshtls" }
linkerd-signal = { path = "../linkerd/signal" }
tokio = { version = "1", features = ["rt", "time", "net"] }
tracing = "0.1"

[target.x86_64-unknown-linux-gnu.dependencies]
jemallocator = { version = "0.3" }
