[package]
name = "linkerd2-opencensus"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
futures = "0.3"
http = "0.2"
http-body = "0.4"
linkerd2-channel = { path = "../channel" }
linkerd2-error = { path = "../error" }
linkerd2-metrics = { path = "../metrics" }
opencensus-proto = { path = "../../opencensus-proto" }
pin-project = "0.4"
tonic = { version = "0.3", default-features = false, features = ["prost", "codegen"] }
tower = { version = "0.4.1", default-features = false }
tracing = "0.1.22"
