[package]
name = "linkerd-opentelemetry"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
http-body = { workspace = true }
linkerd-error = { path = "../error" }
linkerd-metrics = { path = "../metrics" }
opentelemetry = { version = "0.31", default-features = false, features = ["trace"] }
opentelemetry-semantic-conventions = { version = "0.31", features = ["semconv_experimental"] }
opentelemetry_sdk = { version = "0.31", default-features = false, features = ["trace"] }
opentelemetry-proto = { version = "0.31" }
opentelemetry-zipkin = { version = "0.31", default-features = false }
tonic = { workspace = true, default-features = false, features = [
    "codegen",
] }
tracing = { workspace = true }
