[package]
name = "linkerd-proxy-http"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
HTTP-specific implementations that rely on other proxy infrastructure

This should probably be decomposed into smaller, decoupled crates.
"""

[dependencies]
async-trait = "0.1"
bytes = "1"
drain = "0.1"
futures = { version = "0.3", default-features = false }
h2 = "0.3"
http = "1"
http-body = "1"
httparse = "1"
hyper = { version = "1", features = [
    "client",
    "http1",
    "http2",
    "server",
] }
hyper-balance = { path = "../../../hyper-balance" }
hyper-util = { version = "0.1", features = [
    "client",
    "client-legacy",
    "http1",
    "http2",
    "server",
] }
parking_lot = "0.12"
pin-project = "1"
rand = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["rt", "sync", "time"] }
tower = { version = "0.4", default-features = false }
tracing = "0.1"
try-lock = "0.2"

linkerd-detect = { path = "../../detect" }
linkerd-duplex = { path = "../../duplex" }
linkerd-error = { path = "../../error" }
linkerd-http-box = { path = "../../http/box" }
linkerd-http-h2 = { path = "../../http/h2" }
linkerd-http-classify = { path = "../../http/classify" }
linkerd-io = { path = "../../io" }
linkerd-proxy-balance = { path = "../balance" }
linkerd-stack = { path = "../../stack" }

[target.'cfg(fuzzing)'.dependencies]
tokio-test = "0.4"

[dev-dependencies]
tokio-test = "0.4"
tower-test = "0.4"
linkerd-tracing = { path = "../../tracing", features = ["ansi"] }
