
[package]
name = "linkerd2-proxy-http"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
HTTP-specific implementations that rely on other proxy infrastructure

This should probably be decomposed into smaller, decoupled crates.
"""

[dependencies]
bytes = "0.4"
futures = "0.1"
h2 = "0.1"
http = "0.1"
http-body = "0.1"
hyper = "0.12.3"
hyper-balance = { path  = "../../../hyper-balance" }
indexmap = "1.0"
linkerd2-addr = { path  = "../../addr" }
linkerd2-dns = { path  = "../../dns" }
linkerd2-drain = { path  = "../../drain" }
linkerd2-duplex = { path  = "../../duplex" }
linkerd2-error = { path  = "../../error" }
linkerd2-fallback = { path  = "../../fallback" }
linkerd2-identity = { path  = "../../identity" }
linkerd2-router = { path  = "../../router" }
linkerd2-metrics = { path  = "../../metrics" }
linkerd2-stack = { path  = "../../stack" }
linkerd2-timeout = { path  = "../../timeout" }
linkerd2-proxy-transport = { path  = "../transport" }
rand = "0.6.3"
regex = "1.0.0"
tokio = "0.1"
tokio-connect = { git = "https://github.com/carllerche/tokio-connect" }
tokio-timer = "0.2"   # for tokio_timer::clock
tower = "0.1"
tower-balance = { git = "https://github.com/tower-rs/tower" }
tower-discover = "0.1"
tower-load = { git = "https://github.com/tower-rs/tower" }
tower-grpc = { version = "0.1", default-features = false, features = ["protobuf"] }
tower-util = "0.1"
tracing = "0.1.9"
tracing-futures = "0.0.1-alpha.1"
try-lock = "0.2"
