[package]
name = "linkerd-proxy-http"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
HTTP-specific implementations that rely on other proxy infrastructure

This should probably be decomposed into smaller, decoupled crates.
"""

[dependencies]
async-trait = "0.1"
bytes = "1"
drain = "0.1.0"
futures = { version = "0.3", default-features = false }
h2 = "0.3"
http = "0.2"
http-body = "0.4"
httparse = "1.6"
hyper = { version = "0.14.17", features = ["client", "http1", "http2", "server", "stream", "runtime"] }
hyper-balance = { path = "../../../hyper-balance" }
linkerd-detect = { path = "../../detect" }
linkerd-duplex = { path = "../../duplex" }
linkerd-error = { path = "../../error" }
linkerd-http-box = { path = "../../http-box" }
linkerd-io = { path = "../../io" }
linkerd-stack = { path = "../../stack" }
rand = "0.8"
thiserror = "1.0"
tokio = { version = "1", features = ["time", "rt"] }
tower = { version = "0.4.12", default-features = false, features = ["balance", "load", "discover"] }
tracing = "0.1.30"
try-lock = "0.2"
pin-project = "1"

[target.'cfg(fuzzing)'.dependencies]
tokio-test = "0.4"

[dev-dependencies]
tokio-test = "0.4"
linkerd-tracing = { path = "../../tracing", features = ["ansi"] }
