[package]
name = "linkerd2-identity"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"

[features]
default = []
test-util = []

[dependencies]
linkerd2-dns-name = { path = "../dns/name" }
ring = "0.16.19"
rustls = "0.19"
tracing = "0.1.2"
untrusted = "0.7"
webpki = "=0.21.3"

