[package]
name = "linkerd-identity"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"

[features]
default = []
test-util = []

[dependencies]
linkerd-dns-name = { path = "../dns/name" }
ring = "0.16.19"
thiserror = "1.0"
tokio-rustls = "0.22"
tracing = "0.1.26"
untrusted = "0.7"
webpki = "=0.21.4"

