[package]
name = "linkerd-identity"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
prometheus-client = "0.22"
thiserror = "1"
tracing = "0.1"
url = "2.5.4"

linkerd-dns-name = { path = "../dns/name" }
linkerd-metrics = { path = "../metrics" }
linkerd-error = { path = "../error" }
