[package]
name = "linkerd2-request-filter"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3"
tower = { version = "0.3", default-features = false }
tracing = "0.1.18"
linkerd2-error = { path = "../error" }
pin-project = "0.4"