[package]
name = "linkerd2-http-classify"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
http = "0.2"
linkerd2-error = { path  = "../error" }
linkerd2-stack = { path  = "../stack" }
tower = { version = "0.3", default-features = false }
