[package]
name = "linkerd2-http-box"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
bytes = "0.6"
bytes05 = { package = "bytes", version = "0.5" }
futures = "0.3"
http = "0.2"
http-body = "0.3"
linkerd2-error = { path = "../error" }
tower = {version = "0.4", default-features = false }
pin-project = "0.4"