[package]
name = "linkerd-http-route"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
http = "0.2"
regex = "1"
thiserror = "1"
tracing = "0.1"
url = "2"

[dev-dependencies]
maplit = "1"
