[package]
name = "linkerd-proxy-balance"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
futures = { version = "0.3", default-features = false }
rand = "0.9"
tokio = { version = "1", features = ["time"] }
tracing = "0.1"

linkerd-error = { path = "../../error" }
linkerd-metrics = { path = "../../metrics" }
linkerd-pool-p2c = { path = "../../pool/p2c" }
linkerd-proxy-core = { path = "../core" }
linkerd-proxy-balance-gauge-endpoints = { path = "gauge-endpoints" }
linkerd-proxy-balance-queue = { path = "queue" }
linkerd-stack = { path = "../../stack" }

[dependencies.tower]
workspace = true
default-features = false
features = ["load"]
