[package]
name = "linkerd-metrics"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
default = []
summary = ["hdrhistogram"]
test_util = []

[dependencies]
deflate = { version = "1.0.0", features = ["gzip"] }
hdrhistogram = { version = "7.5", default-features = false, optional = true }
http = "0.2"
hyper = { version = "0.14.17", features = ["http1", "http2"] }
linkerd-stack = { path = "../stack", optional = true }
parking_lot = "0.12"
tokio = { version = "1", features = ["time"] }
tracing = "0.1.30"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
tokio = { version = "1", features = ["rt", "macros", "test-util", "time"] }
