[package]
name = "linkerd-metrics"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[features]
default = []
process = ["dep:kubert-prometheus-process"]
stack = ["dep:linkerd-stack"]
test_util = []

[dependencies]
deflate = { version = "1", features = ["gzip"] }
http = { workspace = true }
http-body = { workspace = true }
hyper = { workspace = true, features = ["http1", "http2"] }
kubert-prometheus-process = { version = "0.2", optional = true }
parking_lot = "0.12"
prometheus-client = { workspace = true }
tokio = { version = "1", features = ["time"] }
tracing = "0.1"

linkerd-http-box = { path = "../http/box" }
linkerd-stack = { path = "../stack", optional = true }

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
tokio = { version = "1", features = ["rt", "macros", "test-util", "time"] }
