[package]
name = "linkerd-metrics"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
default = []
process = ["linkerd-system"]
stack = ["linkerd-stack"]
test_util = []

[dependencies]
bytes = "1"
deflate = { version = "1", features = ["gzip"] }
http = "1"
http-body = "1"
http-body-util = "0.1"
linkerd-stack = { path = "../stack", optional = true }
linkerd-system = { path = "../system", optional = true }
parking_lot = "0.12"
prometheus-client = "0.22"
tokio = { version = "1", features = ["time"] }
tracing = "0.1"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
tokio = { version = "1", features = ["rt", "macros", "test-util", "time"] }
