[package]
name = "linkerd2-io"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
General I/O primitives.
"""
[features]
test = ["tokio-test"]

[dependencies]
futures = "0.3"
bytes = "0.5"
linkerd2-errno = { path = "../errno" }
tokio = { version = "0.2", features = ["io-util", "net", "macros"] }
tokio-rustls = "0.13"
pin-project = "0.4"
tokio-test = { version = "0.2", optional = true }

[dev-dependencies]
tokio-test = "0.2"
