[package]
name = "linkerd-io"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
General I/O primitives.
"""

[features]
default = []

[dependencies]
async-trait = "0.1"
futures = { version = "0.3", default-features = false }
bytes = "1"
linkerd-errno = { path = "../errno" }
tokio = { version = "1", features = ["io-util", "net"] }
tokio-test = { version = "0.4", optional = true }
tokio-util = { version = "0.6", features = ["io"] }
pin-project = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
