[package]
name = "linkerd-exp-backoff"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false


[dependencies]
futures = "0.3.9"
rand = { version = "0.8", features = ["small_rng"] }
thiserror = "1.0"
tokio = { version = "1", features = ["time"]}
pin-project = "1"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
