[package]
name = "linkerd-proxy-balance-queue"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
futures = { version = "0.3", default-features = false }
parking_lot = "0.12"
pin-project = "1"
prometheus-client = "0.22"
thiserror = "2"
tokio = { version = "1", features = ["rt", "sync", "time"] }
tokio-util = "0.7"
tracing = "0.1"

linkerd-error = { path = "../../../error" }
linkerd-metrics = { path = "../../../metrics" }
linkerd-proxy-core = { path = "../../core" }
linkerd-pool = { path = "../../../pool" }
linkerd-stack = { path = "../../../stack" }

[dev-dependencies]
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-test = "0.4"
tower-test = "0.4"

linkerd-pool-mock = { path = "../../../pool/mock" }
linkerd-tracing = { path = "../../../tracing" }
