[package]
name = "linkerd-proxy-dns-resolve"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false
description = """
Service Dns Resolutions for the proxy
"""

[dependencies]
futures = { version = "0.3", default-features = false }
linkerd-error = { path = "../../error" }
linkerd-addr = { path = "../../addr" }
linkerd-dns = { path = "../../dns" }
linkerd-proxy-core = { path = "../core" }
linkerd-stack = { path = "../../stack" }
tokio = { version = "1", features = ["sync"] }
tokio-stream = { version = "0.1.7", features = ["sync"]}
tower = "0.4.8"
tracing = "0.1.29"
