[package]
name = "linkerd-proxy-discover"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
Utilities to implement a Discover with the core Resolve type
"""


[dependencies]
futures = { version = "0.3", default-features = false }
linkerd-error = { path = "../../error" }
linkerd-proxy-core = { path = "../core" }
linkerd-stack = { path = "../../stack" }
tokio = { version = "1", features = ["sync", "time"] }
tokio-util = "0.6.8"
tower = { version = "0.4.8", features = ["discover"] }
tracing = "0.1.28"
pin-project = "1"

[dev-dependencies]
async-stream = "0.3"
tokio = { version = "1", features = ["macros", "rt"] }
tower = { version = "0.4.8", default-features = false, features = ["discover", "util"]}
