[package]
name = "linkerd-proxy-discover"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false
description = """
Utilities to implement a Discover with the core Resolve type
"""


[dependencies]
futures = "0.3.9"
linkerd-channel = { path = "../../channel" }
linkerd-error = { path = "../../error" }
linkerd-proxy-core = { path = "../core" }
linkerd-stack = { path = "../../stack" }
tokio = { version = "1", features = ["sync", "time"] }
tracing = "0.1.23"
pin-project = "1"

[dependencies.tower]
version = "0.4"
# disable tower's tracing `log` integration for performance reasons, since we
# will consume tower's traces as traces.
default-features = false
features = ["discover"]

[dev-dependencies]
async-stream = "0.3"
tokio = { version = "1", features = ["macros", "rt"] }
tower = { version = "0.4.1", default-features = false, features = ["discover", "util"]}
