[package]
name = "linkerd2-proxy-discover"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
Utilities to implement a Discover with the core Resolve type
"""


[dependencies]
futures = "0.3"
linkerd2-channel = { path = "../../channel" }
linkerd2-error = { path = "../../error" }
linkerd2-proxy-core = { path = "../core" }
linkerd2-stack = { path = "../../stack" }
tokio = { version = "1", features = ["sync", "time"] }
tracing = "0.1.22"
tracing-futures = { version = "0.2", features = ["std-future"] }
pin-project = "0.4"

[dependencies.tower]
version = "0.4"
# disable tower's tracing `log` integration for performance reasons, since we
# will consume tower's traces as traces.
default-features = false
features = ["discover"]

[dev-dependencies]
async-stream = "0.2"
tokio = { version = "1", features = ["macros", "rt"] }
tower = { version = "0.4.1", default-features = false, features = ["discover", "util"]}
