[package]
name = "linkerd-proxy-tap"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
rustfmt = ["linkerd2-proxy-api/rustfmt"]

[dependencies]
http = "0.2"
hyper = { version = "0.14.2", features = ["http1", "http2"] }
futures = { version = "0.3", default-features = false }
ipnet = "2.3"
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", branch = "main", features = ["tap", "server"] }
linkerd-conditional = { path = "../../conditional" }
linkerd-error = { path = "../../error" }
linkerd-identity = { path = "../../identity" }
linkerd-io = { path = "../../io" }
linkerd-proxy-http = { path = "../http" }
linkerd-proxy-transport = { path = "../transport" }
linkerd-stack = { path = "../../stack" }
linkerd-tls = { path = "../../tls" }
rand = { version = "0.8" }
thiserror = "1.0"
tokio = { version = "1", features = ["time"]}
tower = { version = "0.4.8", default-features = false }
tonic = { version = "0.4", default-features = false }
tracing = "0.1.26"
pin-project = "1"

[dev-dependencies]
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", branch = "main", features = ["arbitrary"] }
prost-types = "0.7.0"
quickcheck = { version = "1", default-features = false }
