[package]
name = "linkerd-proxy-tap"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bytes = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
hyper = { workspace = true, features = ["http1", "http2"] }
hyper-util = { workspace = true, features = ["service"] }
futures = { version = "0.3", default-features = false }
ipnet = "2.11"
linkerd2-proxy-api = { workspace = true, features = ["tap"] }
linkerd-conditional = { path = "../../conditional" }
linkerd-error = { path = "../../error" }
linkerd-meshtls = { path = "../../meshtls" }
linkerd-io = { path = "../../io" }
linkerd-proxy-http = { path = "../http" }
linkerd-stack = { path = "../../stack" }
linkerd-tls = { path = "../../tls" }
parking_lot = "0.12"
prost-types = { workspace = true }
rand = { version = "0.9" }
thiserror = "2"
tokio = { version = "1", features = ["time"] }
tower = { workspace = true, default-features = false }
tonic = { workspace = true, default-features = false }
tracing = "0.1"
pin-project = "1"

[dev-dependencies]
linkerd2-proxy-api = { workspace = true, features = ["arbitrary"] }
quickcheck = { version = "1", default-features = false }
