[package]
name = "linkerd2-proxy-tap"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
http = "0.2"
hyper = { version = "0.14.2", features = ["http1", "http2"] }
futures = "0.3"
indexmap = "1.0"
ipnet = "2.0"
linkerd2-conditional = { path = "../../conditional" }
linkerd2-error = { path = "../../error" }
linkerd2-identity = { path = "../../identity" }
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", tag = "v0.1.17" }
linkerd2-proxy-http = { path = "../http" }
linkerd2-proxy-transport = { path = "../transport" }
linkerd2-stack = { path = "../../stack" }
rand = { version = "0.8" }
tokio = { version = "1", features = ["time"]}
tower = { version = "0.4.1", default-features = false }
tonic = { version = "0.3", default-features = false }
tracing = "0.1.22"
tracing-futures = "0.2"
pin-project = "0.4"

[dev-dependencies]
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", tag = "v0.1.17", features = ["arbitrary"] }
prost-types = "0.7.0"
