[package]
name = "linkerd2-proxy-tap"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
http = "0.2"
hyper = "0.14.0-dev"
futures = "0.3"
indexmap = "1.0"
ipnet = "2.0"
linkerd2-conditional = { path = "../../conditional" }
linkerd2-error = { path = "../../error" }
linkerd2-identity = { path = "../../identity" }
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", branch = "eliza/tokio-0.3" }
linkerd2-proxy-http = { path = "../http" }
linkerd2-proxy-transport = { path = "../transport" }
linkerd2-stack = { path = "../../stack" }
rand = { version = "0.7", features = ["small_rng"] }
tokio = { version = "0.3", features = ["time"]}
tower = {version = "0.4", default-features = false }
tonic = { version = "0.3", default-features = false }
tracing = "0.1.19"
tracing-futures = "0.2"
pin-project = "0.4"

[dev-dependencies]
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", branch = "eliza/tokio-0.3", features = ["arbitrary"] }
prost-types = "0.6.0"
