[package]
name = "linkerd-proxy-identity-client"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
futures = { version = "0.3", default-features = false }
linkerd2-proxy-api = { version = "0.6", features = ["identity"] }
linkerd-error = { path = "../../error" }
linkerd-identity = { path = "../../identity" }
linkerd-metrics = { path = "../../metrics" }
linkerd-stack = { path = "../../stack" }
parking_lot = "0.12"
pin-project = "1"
thiserror = "1"
tokio = { version = "1", features = ["time", "sync"] }
tonic = { version = "0.7", default-features = false }
tracing = "0.1"
http-body = "0.4"
