[package]
name = "linkerd2-drain"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
linkerd2-error = { path = "../error" }
tokio = {version = "0.2.17", features = ["sync", "macros"]}
pin-project = "0.4"
futures = "0.3"

[dev-dependencies]
tokio-test = "0.2"