[package]
name = "linkerd2-proxy-core"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
Core interfaces needed to implement proxy components
"""

[dependencies]
futures = "0.3"
linkerd2-error = { path = "../../error" }
tower = { version = "0.4.1", default-features = false }
pin-project = "0.4"
