[package]
name = "linkerd2-proxy-core"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
futures = "0.1"
linkerd2-error = { path = "../../error" }
tokio = "0.1"
tower = "0.1"
