[package]
name = "linkerd-proxy-api-resolve"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false
description = """
Implements the Resolve trait using the proxy's gRPC API
"""

[features]
rustfmt = ["linkerd2-proxy-api/rustfmt"]

[dependencies]
async-stream = "0.3"
futures = { version = "0.3", default-features = false }
linkerd-addr = { path = "../../addr" }
linkerd-error = { path = "../../error" }
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", branch = "main", features = ["destination", "client"] }
linkerd-proxy-core = { path = "../core" }
linkerd-stack = { path = "../../stack" }
linkerd-tls = { path = "../../tls" }
http = "0.2"
http-body = "0.4"
indexmap = "1.6"
pin-project = "1"
prost = "0.7"
tonic = { version = "0.4", default-features = false }
tower = { version = "0.4.8", default-features = false }
tracing = "0.1.26"
