[package]
name = "linkerd2-proxy-api-resolve"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
Implements the Resolve trait using the proxy's gRPC API
"""

[dependencies]
async-stream = "0.2.1"
futures = "0.3"
linkerd2-identity = { path = "../../identity" }
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", tag = "v0.1.13" }
linkerd2-proxy-core = { path = "../core" }
prost = "0.6"
http = "0.2"
http-body = "0.3"
tonic = { version = "0.2", default-features = false }
indexmap = "1.0"
tower = { version = "0.3", default-features = false }
tracing = "0.1.19"
pin-project = "0.4"
