[package]
name = "linkerd-proxy-api-resolve"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false
description = """
Implements the Resolve trait using the proxy's gRPC API
"""

[dependencies]
async-stream = "0.3"
futures = "0.3.9"
linkerd-addr = { path = "../../addr" }
linkerd2-proxy-api = { git = "https://github.com/linkerd/linkerd2-proxy-api", tag = "v0.1.18" }
linkerd-proxy-core = { path = "../core" }
linkerd-stack = { path = "../../stack" }
linkerd-tls = { path = "../../tls" }
http = "0.2"
http-body = "0.4"
indexmap = "1.0"
pin-project = "1"
prost = "0.7"
tonic = { version = "0.4", default-features = false }
tower = { version = "0.4.1", default-features = false }
tracing = "0.1.23"
