[package]
name = "linkerd-proxy-api-resolve"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
Implements the Resolve trait using the proxy's gRPC API
"""

[dependencies]
futures = { version = "0.3", default-features = false }
linkerd-addr = { path = "../../addr" }
linkerd-error = { path = "../../error" }
linkerd2-proxy-api = { version = "0.13", features = ["destination"] }
linkerd-proxy-core = { path = "../core" }
linkerd-stack = { path = "../../stack" }
linkerd-tonic-stream = { path = "../../tonic-stream" }
linkerd-tls = { path = "../../tls" }
linkerd-identity = { path = "../../identity" }
http = "0.2"
http-body = "1.0"
pin-project = "1"
prost = "0.12"
tonic = { version = "0.10", default-features = false }
tower = { version = "0.4", default-features = false }
tracing = "0.1"
