[package]
name = "linkerd-proxy-api-resolve"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
Implements the Resolve trait using the proxy's gRPC API
"""

[dependencies]
futures = { version = "0.3", default-features = false }
linkerd2-proxy-api = { workspace = true, features = ["destination"] }
linkerd-addr = { path = "../../addr" }
linkerd-error = { path = "../../error" }
linkerd-proxy-core = { path = "../core" }
linkerd-http-h2 = { path = "../../http/h2" }
linkerd-stack = { path = "../../stack" }
linkerd-tonic-stream = { path = "../../tonic-stream" }
linkerd-tls = { path = "../../tls" }
linkerd-identity = { path = "../../identity" }
http = { workspace = true }
http-body = { workspace = true }
pin-project = "1"
prost = { workspace = true }
tonic = { workspace = true, default-features = false }
tower = { version = "0.4", default-features = false }
tracing = "0.1"
