[package]
name = "linkerd2-app-profiling"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
Proxy profiling

This crate provides a binary for running a standalone Linkerd proxy
for profiling and benchmarking.
"""

[dependencies]
linkerd2-app-integration = { path = "../integration" }
tokio = { version = "1", features = ["rt", "net", "macros"]}
