[package]
name = "linkerd-transport-metrics"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2018"
publish = false
description = """Transport-level metrics"""

[dependencies]
futures = { version = "0.3", default-features = false }
linkerd-errno = { path = "../errno" }
linkerd-error = { path = "../error" }
linkerd-io = { path = "../io" }
linkerd-metrics = { path = "../metrics" }
linkerd-stack = { path = "../stack" }
parking_lot = "0.11"
pin-project = "1"
tracing = "0.1.26"
