[package]
name = "linkerd-http-upgrade"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
license = "Apache-2.0"
edition = "2021"
publish = false
description = """
Facilities for HTTP/1 upgrades.
"""

[dependencies]
bytes = { workspace = true }
drain = "0.1"
futures = { version = "0.3", default-features = false }
http = { workspace = true }
http-body = { workspace = true }
hyper = { workspace = true, default-features = false, features = ["deprecated", "client"] }
pin-project = "1"
thiserror = "2"
tokio = { version = "1", default-features = false }
tower = { version = "0.4", default-features = false }
tracing = "0.1"
try-lock = "0.2"

linkerd-duplex = { path = "../../duplex" }
linkerd-error = { path = "../../error" }
linkerd-http-box = { path = "../box" }
linkerd-http-version = { path = "../version" }
linkerd-io = { path = "../../io" }
linkerd-stack = { path = "../../stack" }
