# Builds the proxy as if it were a release.
name: build

permissions:
  contents: read

on:
  pull_request:
    paths:
      # We don't run this workflow on dependency changes. It's mainly intended to determine how long
      # a release build takes given Linkerd changes. We don't really need to run this on every
      # dependabot change, though.
      - "**/*.rs"
      - .github/workflows/build.yml

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  RUSTFLAGS: "-D warnings -A deprecated"

jobs:
  release:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: olix0r/cargo-action-fmt@ee1ef42932e44794821dab57ef1bf7a73df8b21f
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: cargo fetch
      - run: cargo build --release -p linkerd2-proxy --message-format=json | cargo-action-fmt
