# Check all crates.
#
# This workflow checks that `Cargo.lock` is configured sufficiently so that each
# crate can be compiled on its
# own.
name: check-all

permissions:
  contents: read

on:
  pull_request:
    paths:
      - Cargo.lock
      - .github/workflows/check-all.yml
      - justfile

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUSTFLAGS: "-D warnings -A deprecated"

jobs:
  check-all:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v28-rust
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: just fetch
      - run: just check --exclude=linkerd-meshtls-boring
