# Check all crates.
#
# This workflow checks that `Cargo.lock` is configured sufficiently so that each
# crate can be compiled on its
# own.
name: check-all

permissions:
  contents: read

on:
  pull_request:
    paths:
      - Cargo.lock
      - .github/workflows/check-all.yml
      - justfile

env:
  RUSTFLAGS: "-D warnings -A deprecated -C debuginfo=0"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  check-all:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v42-rust
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
      - run: just fetch
      - run: just check --exclude=linkerd-meshtls-boring
      - run: just check --exclude=linkerd-meshtls-boring --features=pprof
