# Check all crates.
#
# This workflow checks that `Cargo.lock` is configured sufficiently so that each
# crate can be compiled on its
# own.
name: check-all

permissions:
  contents: read

on:
  pull_request:
    paths:
      - Cargo.lock
      - .github/workflows/check-all.yml
      - justfile

env:
  RUSTFLAGS: "-D warnings -A deprecated"

jobs:
  check-all:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v38-rust
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - run: just fetch
      - run: just check --exclude=linkerd-meshtls-boring
