# Audits dependencies with cargo-deny
name: deps

permissions:
  contents: read

on:
  pull_request:
    paths:
      - justfile
      - Cargo.lock
      - deny.toml
      - .github/workflows/deps.yml

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -A deprecated"
  RUSTUP_MAX_RETRIES: 10

jobs:
  # Check for security advisories.
  #
  # Failures are not fatal, since issues are opened in the linkerd2 repo via rustsecbot.
  advisories:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: EmbarkStudios/cargo-deny-action@7257a18a9c2fe3f92b85d41ae473520dff953c97
      with:
        command: check advisories

  # Audit licenses, unreleased crates, and unexpected duplicate versions.
  bans:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: EmbarkStudios/cargo-deny-action@7257a18a9c2fe3f92b85d41ae473520dff953c97
      with:
        command: check bans licenses sources

  # Check for upstream deprecations
  deprecated:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v30-rust
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: just fetch
      - run: RUSTFLAGS="-D deprecated" just check --exclude=linkerd-meshtls-boring

