# Run integration tests
name: integration

permissions:
  contents: read

on:
  pull_request:
    paths:
      - Cargo.lock
      - "**/*.rs"
      - "**/*.toml"
      - .github/workflows/integration.yml

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  RUSTFLAGS: "-D warnings -A deprecated"

# Run only the app-level tests. These may take longer to compile (usually due to very large stack
# types) and have the potential to be flakey as they depend on opening sockets and may have timing
# sensitivity.
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container:
      image: docker://rust:1.60.0-bullseye
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: |
          cargo test --no-run \
            --package=linkerd-app \
            --package=linkerd-app-admin \
            --package=linkerd-app-core \
            --package=linkerd-app-gateway \
            --package=linkerd-app-inbound \
            --package=linkerd-app-outbound \
            --package=linkerd-app-test
      - run: |
          cargo test \
            --package=linkerd-app \
            --package=linkerd-app-admin \
            --package=linkerd-app-core \
            --package=linkerd-app-gateway \
            --package=linkerd-app-inbound \
            --package=linkerd-app-outbound \
            --package=linkerd-app-test

      # Integration: enable tests that are flakey in coverage, but disable tests
      # that can be flakey in CI...
      - run: |
          cargo test --no-run \
            --package=linkerd-app-integration \
            --no-default-features --features=flakey-in-coverage
      - run: |
          cargo test \
            --package=linkerd-app-integration \
            --no-default-features --features=flakey-in-coverage
