# Run integration tests
name: integration

permissions:
  contents: read

on:
  pull_request:
    paths:
      - Cargo.lock
      - "**/*.rs"
      - "**/*.toml"
      - justfile
      - .github/workflows/integration.yml

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -A deprecated -C debuginfo=0"
  RUSTUP_MAX_RETRIES: 10

# Run only the app-level tests. These may take longer to compile (usually due to very large stack
# types) and have the potential to be flakey as they depend on opening sockets and may have timing
# sensitivity.
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    container: ghcr.io/linkerd/dev:v43-rust
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
      - run: just fetch
      - run: |
          just test-crate linkerd-app --no-run \
            --package=linkerd-app-core \
            --package=linkerd-app-gateway \
            --package=linkerd-app-inbound \
            --package=linkerd-app-outbound \
            --package=linkerd-app-test
      - run: |
          just test-crate linkerd-app \
            --package=linkerd-app-core \
            --package=linkerd-app-gateway \
            --package=linkerd-app-inbound \
            --package=linkerd-app-outbound \
            --package=linkerd-app-test
      - run: just test-crate linkerd-app-integration --no-default-features --no-run
      - run: just test-crate linkerd-app-integration --no-default-features

